// Run after daemon test:unit: node scripts/firebase-panel.test.mjs (requires Chrome).
// The real UI and entry store, with synthetic records and an isolated Vite server.
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { mkdtemp, mkdir, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createEntryStore } from '../server/daemon/build/test/entryStore.js'

const uiRequire = createRequire(new URL('../server/ui/package.json', import.meta.url))
const daemonRequire = createRequire(new URL('../server/daemon/package.json', import.meta.url))
const { createServer } = await import(uiRequire.resolve('vite'))
const { default: react } = await import(uiRequire.resolve('@vitejs/plugin-react'))
const { chromium } = daemonRequire('playwright-core')
const { WebSocketServer, WebSocket } = daemonRequire('ws')
const sockets = new WebSocketServer({ noServer: true })
const broadcast = message => {
  for (const socket of sockets.clients) if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify(message))
}
const store = createEntryStore(broadcast)
const device = { deviceId: 'firebase-test', deviceName: 'Test phone', appId: 'test.firebase', platform: 'android', connected: true, capabilities: ['firebase'] }
const timestamp = Date.now()
const record = (id, name, userId, params) => ({
  type: 'firebase-analytics-event', id, name, userId, params, timestamp: timestamp + Number(id),
})
const emit = (id, name, userId, params) => store.pushEntry(device.deviceId, record(id, name, userId, params))
emit('1', 'screen_view', '', { screen_name: 'guest_home', count: 0, enabled: false, empty: null })
emit('2', 'select_item', 'alice', { room_id: 'Room-42', currency: 'TWD', value: 9.99, items: [{ item_id: 'nested-42', quantity: 2 }] })
emit('3', 'purchase', 'bob', { room_id: 'Room-99', currency: 'USD', value: 25 })
store.pushEntry('another-device', record('4', 'other_device', 'alice', { currency: 'TWD' }))
assert.equal(store.pushEntry(device.deviceId, record('5', 'invalid', '', [])), false)
const cacheDir = await mkdtemp(join(tmpdir(), 'sniffer-firebase-ui-'))
const screenshotDir = process.env.SNIFFER_SCREENSHOT_DIR ?? join(tmpdir(), 'sniffer-firebase-review')
const server = await createServer({
  configFile: false, root: fileURLToPath(new URL('../server/ui', import.meta.url)), cacheDir,
  plugins: [react()], define: { __APP_VERSION__: JSON.stringify('test') }, server: { host: '127.0.0.1', port: 0 },
})
let browser
try {
  await server.listen()
  server.httpServer.on('upgrade', (request, socket, head) => {
    if (request.url === '/ui') sockets.handleUpgrade(request, socket, head, ws => sockets.emit('connection', ws))
  })
  sockets.on('connection', ws => ws.send(JSON.stringify({ type: 'init', devices: [device], entries: store.snapshot() })))
  browser = await chromium.launch({ channel: 'chrome', headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  page.setDefaultTimeout(5000)
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  let failClear = false
  await page.route('**/api/**', async route => {
    if (route.request().url().endsWith('/api/entries/firebase')) {
      if (failClear) return route.fulfill({ status: 500, json: { error: 'test failure' } })
      store.clearFirebase()
      broadcast({ type: 'firebase-entries-cleared' })
    }
    await route.fulfill({ json: { checks: [] } })
  })
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}`)
  const tab = page.locator('nav.tabs').getByRole('button', { name: /Firebase Beta/ })
  const settings = page.getByTitle('Settings (⌘,)')
  const toggle = page.getByRole('switch', { name: 'Firebase Beta' })
  const panel = page.locator('.firebase-panel')
  const rows = panel.locator('.firebase-event[data-kind="firebase"]')
  const search = page.getByPlaceholder('Search events, params, user ID…')
  assert.equal(await tab.count(), 0)
  await settings.click()
  await toggle.focus()
  await toggle.press('Space')
  await settings.click()
  await tab.click()
  await rows.first().waitFor()
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 3)
  assert.equal(await rows.count(), 3)
  assert.deepEqual(await rows.locator('.firebase-event-message').allTextContents(), ['purchase', 'select_item', 'screen_view'])
  const assertRowAlignment = async () => {
    const centers = await rows.first().evaluate(row => {
      return ['time', '.firebase-event-dot', '.firebase-event-message'].map(selector => {
        const el = row.querySelector(selector)
        const range = document.createRange()
        if (selector === '.firebase-event-dot') {
          const box = el.getBoundingClientRect()
          return box.y + box.height / 2
        }
        range.selectNodeContents(el)
        const box = range.getBoundingClientRect()
        return box.y + box.height / 2
      })
    })
    assert.ok(Math.max(...centers) - Math.min(...centers) <= 1.5, `Time, dot and name centers: ${centers}`)
  }
  await assertRowAlignment()
  assert.equal(await panel.locator('input[type=search]').count(), 0, 'The panel uses the shared search field')
  const users = panel.getByRole('complementary', { name: 'Firebase user filters' })
  await panel.getByTitle('Filter this column').click()
  await panel.locator('label.filter-switch').click()
  await panel.getByPlaceholder('Name contains…').fill('SELECT')
  assert.equal(await rows.count(), 3, 'A filter draft is not applied before adding it')
  await panel.getByPlaceholder('Name contains…').press('Enter')
  await page.waitForFunction(() => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === 1)
  assert.match(await rows.first().innerText(), /select_item/, 'Name rules match partial names without case sensitivity')
  await panel.getByTitle('Remove', { exact: true }).click()
  await panel.getByTitle('Filter this column').click()
  await page.waitForFunction(() => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === 3)
  const detail = panel.getByRole('region', { name: /^Parameters for / })
  const expand = async row => { if (await row.getAttribute('aria-expanded') !== 'true') await row.click() }
  await expand(rows.nth(0))
  await expand(rows.nth(1))
  assert.equal(await detail.count(), 2, 'Multiple events can stay expanded')
  await panel.getByRole('button', { name: 'Collapse all', exact: true }).click()
  assert.equal(await detail.count(), 0, 'Collapse all closes every expanded event')
  assert.equal(await panel.getByRole('button', { name: 'Collapse all', exact: true }).isDisabled(), true)
  await expand(rows.nth(0))
  await expand(rows.nth(1))
  await rows.nth(0).click()
  assert.equal(await detail.count(), 1, 'Collapsing one event preserves the other')
  assert.equal(await rows.nth(1).getAttribute('aria-expanded'), 'true')
  await rows.nth(1).click()
  assert.equal(await panel.getByLabel('Firebase severity').count(), 0)
  assert.equal(await panel.locator('.firebase-event[data-latest]').count(), 1)
  assert.equal(await rows.first().locator('.firebase-event-dot').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(91, 72, 217)')
  assert.equal(await rows.first().locator('.firebase-event-meta').count(), 0)
  await search.fill('room_ID')
  await page.waitForFunction(() => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === 2)
  await expand(rows.filter({ hasText: 'select_item' }))
  assert.match(await detail.innerText(), /9.99/)
  assert.match(await detail.innerText(), /nested-42/)
  assert.equal(await detail.locator('.kv-k mark').innerText(), 'room_id')
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await detail.locator('.kv').filter({ has: page.locator('.kv-k', { hasText: /^room_id$/ }) }).getByRole('button', { name: 'Copy', exact: true }).click()
  assert.deepEqual(JSON.parse(await page.evaluate(() => navigator.clipboard.readText())), { room_id: 'Room-42' })
  await search.fill('twd')
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1)
  assert.equal(await detail.locator('.kv-v mark').innerText(), 'TWD')
  await users.getByRole('button', { name: /^bob/ }).click()
  await panel.getByText('No matching results').waitFor()
  await users.getByRole('button', { name: /^All users/ }).click()
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1)
  await search.fill('purchase')
  await rows.filter({ hasText: 'purchase' }).waitFor()
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1)
  await search.fill('select')
  await rows.first().waitFor()
  await search.fill('')
  await search.fill('nested-42')
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1)
  await expand(rows.first())
  assert.match(await detail.locator('mark').innerText(), /nested-42/)
  await rows.first().click({ button: 'right' })
  await page.getByText('Copy name', { exact: true }).waitFor()
  await page.keyboard.press('Escape')
  await search.fill('does-not-exist')
  await panel.getByText('No matching results').waitFor()
  await panel.getByRole('button', { name: 'Clear filters' }).click()
  assert.equal(await search.inputValue(), '')
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 3)
  assert.equal(await rows.count(), 3)
  await search.fill('false')
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1)
  await expand(rows.first())
  assert.match(await detail.innerText(), /guest_home/)
  await rows.first().click()
  assert.equal(await detail.count(), 0, 'Clicking the expanded event collapses params')
  await expand(rows.first())
  assert.equal(await panel.locator('.detail-pane').count(), 0, 'Analytics does not open a sidebar')
  await search.fill('null')
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1)
  await search.fill('ScReEn_V')
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1, 'The panel search also matches partial event names, ignoring case')
  assert.match(await rows.first().innerText(), /screen_view/)
  assert.equal(await rows.first().locator('.firebase-event-message mark').innerText(), 'screen_v')
  await search.fill('ALIce')
  await rows.filter({ hasText: 'select_item' }).waitFor()
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1, 'Shared search matches user IDs')
  await search.fill('')
  await users.getByRole('button', { name: /^No user ID/ }).click()
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1)
  await users.getByRole('button', { name: /^All users/ }).click()
  store.pushEntry(device.deviceId, { type: 'http-request', id: 'http', timestamp, method: 'GET', url: 'https://example.com/rooms', library: 'okhttp', headers: {}, body: null, userId: 'alice' })
  const apiRows = panel.locator('.firebase-event[data-kind="http"]')
  await apiRows.first().waitFor()
  await search.fill('TWD')
  await page.waitForFunction(n => document.querySelectorAll('.firebase-event[data-kind="firebase"]').length === n, 1)
  assert.equal(await rows.count(), 1)
  assert.equal(await apiRows.count(), 0, 'Shared search filters API context too')
  await expand(rows.first())
  await mkdir(screenshotDir, { recursive: true })
  await page.screenshot({ path: join(screenshotDir, 'analytics-desktop.png'), fullPage: true })
  await page.evaluate(() => document.documentElement.dataset.theme = 'dark')
  await page.screenshot({ path: join(screenshotDir, 'analytics-dark.png'), fullPage: true })
  await page.evaluate(() => delete document.documentElement.dataset.theme)
  await page.setViewportSize({ width: 390, height: 844 })
  await assertRowAlignment()
  await page.screenshot({ path: join(screenshotDir, 'analytics-mobile.png'), fullPage: true })
  assert.equal(await panel.locator('.list-pane').isVisible(), true)
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.evaluate(() => {
    window.eventAnimations = []
    const animate = Element.prototype.animate
    Element.prototype.animate = function (frames, options) {
      if (this.matches('.firebase-event-body')) window.eventAnimations.push({ id: this.closest('.firebase-event').dataset.entryId, frames, options })
      return animate.call(this, frames, options)
    }
  })
  emit('6', 'live_event', 'alice', { currency: 'TWD' })
  await rows.filter({ hasText: 'live_event' }).waitFor()
  assert.match(await rows.first().innerText(), /live_event/, 'Newest events appear first')
  assert.equal(await rows.filter({ hasText: 'select_item' }).getAttribute('aria-expanded'), 'true', 'Live arrivals preserve expanded params')
  assert.equal(await rows.first().getAttribute('aria-expanded'), 'false', 'Selection does not expand new arrivals')
  const arrivals = await page.evaluate(() => window.eventAnimations)
  assert.equal(arrivals.length, 1, 'Only the new event animates')
  assert.equal(arrivals[0].frames[0].transform, 'translateX(12px)')
  assert.equal(arrivals[0].options.duration, 220)
  await search.fill('no-such-param')
  await search.fill('TWD')
  assert.equal(await page.evaluate(() => window.eventAnimations.length), 1, 'Filtering does not replay animations')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  emit('7', 'reduced_motion_event', 'alice', { currency: 'TWD' })
  await rows.filter({ hasText: 'reduced_motion_event' }).waitFor()
  const reduced = await page.evaluate(() => window.eventAnimations.at(-1))
  assert.equal(reduced.frames[0].transform, undefined, 'Reduced motion fades without sliding')
  await panel.getByRole('button', { name: 'Clear Firebase' }).click()
  assert.equal(store.snapshot().filter(e => e.message.type === 'firebase-analytics-event').length, 0)
  assert.equal(store.snapshot().filter(e => e.message.type === 'http-request').length, 1)
  emit('2', 'select_item', 'alice', { currency: 'TWD' })
  assert.equal(store.snapshot().filter(e => e.message.type === 'firebase-analytics-event').length, 0)
  assert.deepEqual(errors, [])
  console.log('Analytics event, params search, user filter, nested/typed params, API context, clear and mobile checks passed')
} finally {
  await browser?.close()
  for (const socket of sockets.clients) socket.terminate()
  sockets.close()
  await server.close()
  await rm(cacheDir, { recursive: true, force: true })
}
